#ifndef CONSTANTES_HPP
#define CONSTANTES_HPP

enum{ DISPLAY_COMPONENT, POSITION_COMPONENT };

enum{ DISPLAY_SYSTEM };

const unsigned int COMPONENT_NOT_FOUND = 1000, SYSTEM_NOT_FOUND = 1001, NUMBR_COMPONENT = 2;
#endif // CONSTANTES_HPP
